### ISSUE TITLE
Contraseñas

### ISSUE THREAD

**Issue by IraitzM** [amejosecar/ELECEUROPEAS2024#2]
## Recomendación

Tengan cuidado con guardar contraseñas en el repositorio ya que cualquiera puede leer el contenido del mismo y por lo tanto conectarse a sus sistemas. Por seguridad cámbienla e intenten no tenerla de manera explícita en los notebooks.

Recomendación: https://blog.gitguardian.com/how-to-handle-secrets-in-python/

**Comment by alejokawaii** [comment]
Resuelto. Contraseña ya no está en abierto en Git y la hemos cambiado.
